[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.5.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/botless/events"
  revision = "d838d0665d9f35c151aad8d2275e9b2abf211569"

[[constraint]]
  name = "github.com/mattmoor/bindings"
  branch = "master"

[[constraint]]
  name = "github.com/cloudevents/sdk-go"
  version = "v0.10.0"
