apiVersion: v1
kind: Secret
metadata:
  name: slack
type: Opaque
data:
  BOT_TOKEN: ZGVmYXVsdA==               # TODO: fill these out with your API keys.
  VERIFICATION_TOKEN: ZGVmYXVsdA==
  BOT_ID: ZGVmYXVsdA==
  CHANNEL_ID: ZGVmYXVsdA==
