# The Slack Source.
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: slack
spec:
  image: github.com/botless/slack/cmd/rtm/
  args: 
    - '--sink=http://default-broker.default.svc.cluster.local'
  env:
  - name: BOT_PORT
    value: "8080"
  - name: BOT_TOKEN
    valueFrom:
      secretKeyRef:
        name: slack
        key: BOT_TOKEN
  - name: VERIFICATION_TOKEN
    valueFrom:
      secretKeyRef:
        name: slack
        key: VERIFICATION_TOKEN
  - name: BOT_ID
    valueFrom:
      secretKeyRef:
        name: slack
        key: BOT_ID
  - name: CHANNEL_ID
    valueFrom:
      secretKeyRef:
        name: slack
        key: CHANNEL_ID
---

# Needed for the broker to POST to the source pod.
apiVersion: v1
kind: Service
metadata:
  name: slack
spec:
  selector:
    source: slack
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---

apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: slack-response
spec:
  filter:
    sourceAndType:
      type: botless.bot.response
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: slack

---

# Needed by the Slack Source to communicate with Slack.
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: slack-ext
spec:
  hosts:
  - "*.slack.com"
  - "slack.com"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
