apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack
  labels:
    slack: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      source: slack
  template:
    metadata:
      labels:
        source: slack
    spec:
      containers:
        - name: slack
          image: github.com/botless/slack/cmd/source
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: SINK
              value: http://sockeye.default.svc.cluster.local

---

apiVersion: v1
kind: Service
metadata:
  name: slack
spec:
  selector:
    source: slack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
