apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: slack
  labels:
    slack: bot
spec:
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sockeye
  template:
    spec:
      containers:
        - name: slack
          image: github.com/botless/slack/cmd/source
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

---

apiVersion: v1
kind: Service
metadata:
  name: slack
spec:
  selector:
    source: slack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
